class_name CharacterModel
extends Node3D
## Humanoid visual built from the CC0 Quaternius "Universal Base Characters"
## (body + hair) driven by the CC0 "Universal Animation Library" 1 & 2.
## Clothing variants are painted textures generated by tools/py/gen_outfits.py.

const BODY_SCENES := {
	"male": "res://assets/characters/male.glb",
	"female": "res://assets/characters/female.glb",
}
const BODY_MESH := {"male": "SuperHero_Male", "female": "Superhero_Female"}
const HAIR_SCENES := {
	"buzzed": "res://assets/characters/hair_buzzed.glb",
	"parted": "res://assets/characters/hair_simpleparted.glb",
	"long": "res://assets/characters/hair_long.glb",
	"buns": "res://assets/characters/hair_buns.glb",
	"buzzed_f": "res://assets/characters/hair_buzzedfemale.glb",
	"beard": "res://assets/characters/hair_beard.glb",
}
const HAIR_COLORS := [
	Color(0.35, 0.3, 0.28), Color(0.2, 0.17, 0.15), Color(0.55, 0.42, 0.3),
	Color(0.75, 0.6, 0.4), Color(0.12, 0.11, 0.11), Color(0.6, 0.35, 0.22), Color(0.75, 0.75, 0.75),
]

const UPPER_BODY_BONES := [
	"spine_02", "spine_03", "neck_01", "Head",
	"clavicle_l", "upperarm_l", "lowerarm_l", "hand_l",
	"clavicle_r", "upperarm_r", "lowerarm_r", "hand_r",
	"index_01_l", "index_02_l", "index_03_l", "middle_01_l", "middle_02_l", "middle_03_l",
	"pinky_01_l", "pinky_02_l", "pinky_03_l", "ring_01_l", "ring_02_l", "ring_03_l",
	"thumb_01_l", "thumb_02_l", "thumb_03_l",
	"index_01_r", "index_02_r", "index_03_r", "middle_01_r", "middle_02_r", "middle_03_r",
	"pinky_01_r", "pinky_02_r", "pinky_03_r", "ring_01_r", "ring_02_r", "ring_03_r",
	"thumb_01_r", "thumb_02_r", "thumb_03_r",
]

## Full body locomotion / action states.
const LOCO_STATES := [
	"Idle", "Walk", "Jog_Fwd", "Sprint", "Crouch_Idle", "Crouch_Fwd",
	"Jump_Start", "Jump", "Jump_Land", "Roll", "Swim_Idle", "Swim_Fwd",
	"Driving", "Sitting_Idle", "Death01", "Hit_Chest", "Hit_Knockback", "LayToIdle",
	"Idle_Talking", "Idle_TalkingPhone", "Idle_FoldArms", "Dance", "Walk_Formal",
	"Punch_Jab", "Punch_Cross", "Melee_Hook", "OverhandThrow", "Interact", "PickUp_Table",
	"Fixing_Kneeling", "Zombie_Walk_Fwd", "Idle_No", "Yes", "ClimbUp_1m", "Push",
]
## Upper body overlay states (aiming, reloading, punching while moving).
const UPPER_STATES := ["Pistol_Idle", "Pistol_Reload", "Pistol_Shoot", "Punch_Jab", "Punch_Cross", "OverhandThrow", "Idle_TalkingPhone"]

static var _anim_lib: AnimationLibrary
static var _outfit_manifest: Dictionary
static var _mat_cache: Dictionary = {}
static var _scene_cache: Dictionary = {}
static var _tree_root: AnimationNodeBlendTree

var gender := "male"
var outfit_file := ""
var skeleton: Skeleton3D
var anim_player: AnimationPlayer
var anim_tree: AnimationTree
var body: MeshInstance3D
var _loco_pb: AnimationNodeStateMachinePlayback
var _upper_pb: AnimationNodeStateMachinePlayback
var _aim_blend := 0.0
var _aim_target := 0.0
var current_loco := "Idle"
var current_upper := ""


static func load_scene(path: String) -> PackedScene:
	if not _scene_cache.has(path):
		_scene_cache[path] = load(path)
	return _scene_cache[path]


static func get_anim_library() -> AnimationLibrary:
	if _anim_lib:
		return _anim_lib
	_anim_lib = AnimationLibrary.new()
	for p in ["res://assets/characters/anim_ual1.glb", "res://assets/characters/anim_ual2.glb"]:
		var s: Node = load_scene(p).instantiate()
		var ap: AnimationPlayer = s.get_node("AnimationPlayer")
		var lib: AnimationLibrary = ap.get_animation_library("")
		for n in lib.get_animation_list():
			if not _anim_lib.has_animation(n):
				_anim_lib.add_animation(n, lib.get_animation(n))
		s.free()
	# Loop fixes for locomotion clips that must cycle
	for n in ["Idle", "Walk", "Jog_Fwd", "Sprint", "Crouch_Idle", "Crouch_Fwd", "Jump", "Swim_Idle", "Swim_Fwd",
			"Driving", "Sitting_Idle", "Idle_Talking", "Idle_TalkingPhone", "Idle_FoldArms", "Dance", "Walk_Formal",
			"Pistol_Idle", "Zombie_Walk_Fwd", "Push", "Idle_No"]:
		if _anim_lib.has_animation(n):
			_anim_lib.get_animation(n).loop_mode = Animation.LOOP_LINEAR
	return _anim_lib


static func get_outfits(p_gender: String) -> Array:
	if _outfit_manifest.is_empty():
		var f := FileAccess.open("res://assets/characters/outfits/manifest.json", FileAccess.READ)
		if f:
			_outfit_manifest = JSON.parse_string(f.get_as_text())
	return _outfit_manifest.get(p_gender, [])


static func pick_outfit(p_gender: String, kind := "", rng: RandomNumberGenerator = null) -> String:
	var list := get_outfits(p_gender)
	var pool: Array = []
	for o in list:
		if kind == "" and o["outfit"] in ["police", "swat", "medic", "jason", "lucia"]:
			continue
		if kind != "" and not String(o["outfit"]).begins_with(kind):
			continue
		pool.append(o["file"])
	if pool.is_empty():
		return list[0]["file"] if list.size() > 0 else ""
	if rng:
		return pool[rng.randi() % pool.size()]
	return pool.pick_random()


static func _build_tree_root() -> AnimationNodeBlendTree:
	if _tree_root:
		return _tree_root
	var bt := AnimationNodeBlendTree.new()
	var loco := AnimationNodeStateMachine.new()
	for s in LOCO_STATES:
		var n := AnimationNodeAnimation.new()
		n.animation = s
		loco.add_node(s, n)
	_connect_all(loco, LOCO_STATES, 0.18)
	var upper := AnimationNodeStateMachine.new()
	var aim := AnimationNodeBlendSpace1D.new()
	for pair in [["Pistol_Aim_Down", -1.0], ["Pistol_Aim_Neutral", 0.0], ["Pistol_Aim_Up", 1.0]]:
		var a := AnimationNodeAnimation.new()
		a.animation = pair[0]
		aim.add_blend_point(a, pair[1], -1, StringName(pair[0]))
	aim.min_space = -1.0
	aim.max_space = 1.0
	upper.add_node("Aim", aim)
	var ustates: Array = ["Aim"]
	for s in UPPER_STATES:
		var n := AnimationNodeAnimation.new()
		n.animation = s
		upper.add_node(s, n)
		ustates.append(s)
	_connect_all(upper, ustates, 0.1)
	bt.add_node("loco", loco)
	bt.add_node("upper", upper)
	var ts := AnimationNodeTimeScale.new()
	bt.add_node("loco_speed", ts)
	var blend := AnimationNodeBlend2.new()
	blend.filter_enabled = true
	for b in UPPER_BODY_BONES:
		blend.set_filter_path(NodePath("Armature/Skeleton3D:" + b), true)
	bt.add_node("upper_blend", blend)
	bt.connect_node("loco_speed", 0, "loco")
	bt.connect_node("upper_blend", 0, "loco_speed")
	bt.connect_node("upper_blend", 1, "upper")
	bt.connect_node("output", 0, "upper_blend")
	_tree_root = bt
	return bt


static func _connect_all(sm: AnimationNodeStateMachine, states: Array, xfade: float) -> void:
	var start := AnimationNodeStateMachineTransition.new()
	start.advance_mode = AnimationNodeStateMachineTransition.ADVANCE_MODE_AUTO
	sm.add_transition("Start", states[0], start)
	for a in states:
		for b in states:
			if a == b:
				continue
			var t := AnimationNodeStateMachineTransition.new()
			t.xfade_time = xfade
			t.switch_mode = AnimationNodeStateMachineTransition.SWITCH_MODE_IMMEDIATE
			t.advance_mode = AnimationNodeStateMachineTransition.ADVANCE_MODE_ENABLED
			sm.add_transition(a, b, t)


func build(p_gender: String, p_outfit := "", hair := "", hair_color := Color(-1, 0, 0), beard := false) -> void:
	gender = p_gender
	var body_scene: Node3D = load_scene(BODY_SCENES[gender]).instantiate()
	body_scene.name = "Body"
	add_child(body_scene)
	# UBC models face +Z; our characters face -Z (Godot forward)
	body_scene.rotation.y = PI
	skeleton = body_scene.get_node("Armature/Skeleton3D")
	body = skeleton.get_node(BODY_MESH[gender])
	outfit_file = p_outfit if p_outfit != "" else pick_outfit(gender)
	if outfit_file != "":
		body.material_override = _outfit_material(outfit_file)
	for mi in skeleton.get_children():
		if mi is MeshInstance3D:
			mi.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_ON
	if hair == "":
		hair = ["buzzed", "parted", "buzzed"].pick_random() if gender == "male" else ["long", "buns", "buzzed_f", "long"].pick_random()
	if hair_color.r < 0:
		hair_color = HAIR_COLORS.pick_random()
	if hair != "none":
		_attach_rigged(HAIR_SCENES[hair], hair_color)
	if beard:
		_attach_rigged(HAIR_SCENES["beard"], hair_color)
	# Animation
	anim_player = AnimationPlayer.new()
	anim_player.name = "AnimationPlayer"
	body_scene.add_child(anim_player)
	anim_player.root_node = NodePath("..")
	anim_player.add_animation_library("", get_anim_library())
	anim_tree = AnimationTree.new()
	anim_tree.name = "AnimationTree"
	body_scene.add_child(anim_tree)
	anim_tree.anim_player = anim_tree.get_path_to(anim_player)
	anim_tree.root_node = NodePath("..")
	anim_tree.tree_root = _build_tree_root()
	anim_tree.callback_mode_process = AnimationMixer.ANIMATION_CALLBACK_MODE_PROCESS_MANUAL
	anim_tree.active = true
	_loco_pb = anim_tree.get("parameters/loco/playback")
	_upper_pb = anim_tree.get("parameters/upper/playback")
	anim_tree.set("parameters/upper_blend/blend_amount", 0.0)
	anim_tree.set("parameters/loco_speed/scale", 1.0)


func _attach_rigged(path: String, color: Color) -> void:
	var s: Node = load_scene(path).instantiate()
	for mi in s.find_children("*", "MeshInstance3D", true, false):
		var m: MeshInstance3D = mi
		m.get_parent().remove_child(m)
		m.owner = null
		skeleton.add_child(m)
		m.skeleton = NodePath("..")
		var mat = m.get_active_material(0)
		if mat is StandardMaterial3D:
			var key = str(mat.get_instance_id()) + str(color)
			if not _mat_cache.has(key):
				var m2: StandardMaterial3D = mat.duplicate()
				m2.albedo_color = color * 2.2
				_mat_cache[key] = m2
			m.material_override = _mat_cache[key]
	s.free()


func _outfit_material(file: String) -> Material:
	var key := gender + "/" + file
	if _mat_cache.has(key):
		return _mat_cache[key]
	var base = body.get_active_material(0)
	var m: StandardMaterial3D = base.duplicate() if base is StandardMaterial3D else StandardMaterial3D.new()
	var tex = load("res://assets/characters/outfits/" + file)
	if tex:
		m.albedo_texture = tex
	_mat_cache[key] = m
	return m


func set_outfit(file: String) -> void:
	outfit_file = file
	body.material_override = _outfit_material(file)


## Locomotion / full body state (cross-faded).
func play(state: String, speed := 1.0) -> void:
	if not _loco_pb:
		return
	anim_tree.set("parameters/loco_speed/scale", speed)
	if state == current_loco:
		return
	current_loco = state
	_loco_pb.travel(state)


func restart(state: String, speed := 1.0) -> void:
	if not _loco_pb:
		return
	anim_tree.set("parameters/loco_speed/scale", speed)
	current_loco = state
	_loco_pb.start(state, true)


## Upper body overlay. Pass "" to fade it out.
func upper(state: String) -> void:
	if not _upper_pb:
		return
	if state == "":
		_aim_target = 0.0
		return
	_aim_target = 1.0
	if state != current_upper or state in ["Pistol_Shoot", "Punch_Jab", "Punch_Cross", "OverhandThrow", "Pistol_Reload"]:
		if state in ["Pistol_Shoot", "Punch_Jab", "Punch_Cross", "OverhandThrow", "Pistol_Reload"]:
			_upper_pb.start(state, true)
		else:
			_upper_pb.travel(state)
	current_upper = state


func set_aim_pitch(v: float) -> void:
	if anim_tree:
		anim_tree.set("parameters/upper/Aim/blend_position", clampf(v, -1.0, 1.0))


func loco_time_left() -> float:
	if not _loco_pb:
		return 0.0
	return _loco_pb.get_current_length() - _loco_pb.get_current_play_position()


func upper_time_left() -> float:
	if not _upper_pb:
		return 0.0
	return _upper_pb.get_current_length() - _upper_pb.get_current_play_position()


var _anim_acc := 0.0
var _anim_skip := 0
var always_full_rate := false


func _process(delta: float) -> void:
	if anim_tree == null:
		return
	_aim_blend = move_toward(_aim_blend, _aim_target, delta * 6.0)
	anim_tree.set("parameters/upper_blend/blend_amount", _aim_blend)
	# animation LOD: far / off-screen characters update less often
	_anim_acc += delta
	var step := 1
	if not always_full_rate:
		var cam := get_viewport().get_camera_3d()
		if cam:
			var to := global_position - cam.global_position
			var d2 := to.length_squared()
			if d2 > 6400.0:
				step = 6
			elif d2 > 1600.0:
				step = 3
			elif d2 > 400.0:
				step = 2
			if d2 > 100.0 and to.dot(-cam.global_basis.z) < 0.0:
				step = maxi(step, 6)
	_anim_skip += 1
	if _anim_skip >= step:
		_anim_skip = 0
		anim_tree.advance(_anim_acc)
		_anim_acc = 0.0


func bone_global(bone: String) -> Vector3:
	var i := skeleton.find_bone(bone)
	if i < 0:
		return global_position
	return skeleton.global_transform * skeleton.get_bone_global_pose(i).origin


func attach_to_bone(node: Node3D, bone: String) -> BoneAttachment3D:
	var ba := BoneAttachment3D.new()
	ba.bone_name = bone
	skeleton.add_child(ba)
	ba.add_child(node)
	return ba
